# Generated by Django 6.1.1 on 2026-09-03 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(db_index=True, max_length=30, unique=True, verbose_name='Номер заказа')),
                ('customer_name', models.CharField(max_length=120, verbose_name='Имя клиента')),
                ('customer_phone', models.CharField(max_length=30, verbose_name='Телефон (+998)')),
                ('delivery_method', models.CharField(choices=[('COURIER', 'Доставка курьером'), ('PICKUP', 'Самовывоз из магазина')], default='COURIER', max_length=20, verbose_name='Способ доставки')),
                ('delivery_city', models.CharField(default='Ташкент', max_length=100, verbose_name='Город/Регион')),
                ('delivery_address', models.TextField(blank=True, verbose_name='Адрес доставки')),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Стоимость доставки (UZS)')),
                ('notes', models.TextField(blank=True, verbose_name='Комментарий к заказу')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Скидка по промокоду (UZS)')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Сумма товаров (UZS)')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Итоговая сумма (UZS)')),
                ('payment_method', models.CharField(choices=[('CLICK', 'Click'), ('PAYME', 'Payme'), ('UZUM', 'Uzum Pay'), ('CASH', 'Наличными при получении'), ('TERMINAL', 'Картой курьеру (терминал)')], default='CASH', max_length=20, verbose_name='Способ оплаты')),
                ('payment_status', models.CharField(choices=[('PENDING', 'Ожидает оплаты'), ('PAID', 'Оплачено'), ('FAILED', 'Ошибка оплаты'), ('REFUNDED', 'Возврат')], default='PENDING', max_length=20, verbose_name='Статус оплаты')),
                ('status', models.CharField(choices=[('NEW', 'Новый'), ('PROCESSING', 'В обработке'), ('IN_DELIVERY', 'Доставляется'), ('COMPLETED', 'Выполнен'), ('CANCELLED', 'Отменен')], default='NEW', max_length=20, verbose_name='Статус заказа')),
                ('telegram_user_id', models.BigIntegerField(blank=True, null=True, verbose_name='Telegram User ID')),
                ('source', models.CharField(choices=[('WEB', 'Веб-витрина'), ('TMA', 'Telegram Mini App'), ('INSTAGRAM', 'Instagram')], default='WEB', max_length=20, verbose_name='Источник заказа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='stores.store', verbose_name='Магазин')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, verbose_name='Название товара (снапшот)')),
                ('variation_name', models.CharField(blank=True, max_length=100, verbose_name='Вариант (снапшот)')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена за единицу (UZS)')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Итого (UZS)')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='Заказ')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='catalog.product', verbose_name='Товар')),
                ('variation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.productvariation', verbose_name='Вариант')),
            ],
            options={
                'verbose_name': 'Позиция заказа',
                'verbose_name_plural': 'Позиции заказа',
            },
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=50, verbose_name='Промокод')),
                ('discount_type', models.CharField(choices=[('PERCENT', 'Процент (%)'), ('FIXED', 'Фиксированная сумма (UZS)')], default='PERCENT', max_length=20, verbose_name='Тип скидки')),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Размер скидки (% или UZS)')),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Минимальная сумма заказа (UZS)')),
                ('max_uses', models.PositiveIntegerField(default=100, verbose_name='Максимальное кол-во использований')),
                ('times_used', models.PositiveIntegerField(default=0, verbose_name='Использовано раз')),
                ('valid_from', models.DateTimeField(blank=True, null=True, verbose_name='Действует с')),
                ('valid_until', models.DateTimeField(blank=True, null=True, verbose_name='Действует до')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_codes', to='stores.store', verbose_name='Магазин')),
            ],
            options={
                'verbose_name': 'Промокод',
                'verbose_name_plural': 'Промокоды',
                'unique_together': {('store', 'code')},
            },
        ),
        migrations.AddField(
            model_name='order',
            name='promo_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='orders.promocode', verbose_name='Промокод'),
        ),
    ]
