# Generated by Django 6.1.1 on 2026-09-03 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('stores', '0002_store_about_us_ru_store_about_us_uz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='bonus_spent',
            field=models.PositiveIntegerField(default=0, verbose_name='Списано бонусов'),
        ),
        migrations.AddField(
            model_name='order',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='stores.branch', verbose_name='Филиал'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_lat',
            field=models.FloatField(blank=True, null=True, verbose_name='Широта доставки'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_lng',
            field=models.FloatField(blank=True, null=True, verbose_name='Долгота доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[('COURIER', 'Доставка курьером'), ('PICKUP', 'Самовывоз из филиала')], default='COURIER', max_length=20, verbose_name='Способ доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('NEW', 'Новый'), ('PROCESSING', 'В процессе'), ('READY', 'Готов к выдаче'), ('IN_DELIVERY', 'Доставляется'), ('COMPLETED', 'Выполнен'), ('CANCELLED', 'Отменен')], default='NEW', max_length=20, verbose_name='Статус заказа'),
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_phone', models.CharField(db_index=True, max_length=30, verbose_name='Телефон клиента')),
                ('customer_name', models.CharField(default='Покупатель', max_length=120, verbose_name='Имя клиента')),
                ('sender', models.CharField(choices=[('CUSTOMER', 'Покупатель'), ('MERCHANT', 'Мерчант / Магазин')], default='CUSTOMER', max_length=20)),
                ('message', models.TextField(verbose_name='Текст сообщения')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время отправки')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='stores.store', verbose_name='Магазин')),
            ],
            options={
                'verbose_name': 'Сообщение в чате',
                'verbose_name_plural': 'Сообщения в чате',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='MarketingBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Заголовок баннера')),
                ('subtitle', models.CharField(blank=True, max_length=200, verbose_name='Подзаголовок / Оффер')),
                ('image', models.ImageField(blank=True, null=True, upload_to='banners/', verbose_name='Картинка баннера')),
                ('image_url', models.URLField(blank=True, max_length=500, verbose_name='Или прямая ссылка на изображение')),
                ('link', models.CharField(blank=True, default='/', max_length=255, verbose_name='Ссылка для перехода')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banners', to='stores.store', verbose_name='Магазин')),
            ],
            options={
                'verbose_name': 'Промо-баннер витрины',
                'verbose_name_plural': 'Промо-баннеры витрины',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MarketingCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название рассылки')),
                ('channel', models.CharField(choices=[('SMS', 'SMS-сообщение'), ('TELEGRAM', 'Telegram-рассылка')], default='TELEGRAM', max_length=20)),
                ('message', models.TextField(verbose_name='Текст сообщения рассылки')),
                ('sent_count', models.PositiveIntegerField(default=0, verbose_name='Отправлено получателям')),
                ('status', models.CharField(choices=[('DRAFT', 'Черновик'), ('SENT', 'Отправлено')], default='SENT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketing_campaigns', to='stores.store', verbose_name='Магазин')),
            ],
            options={
                'verbose_name': 'Маркетинговая рассылка',
                'verbose_name_plural': 'Маркетинговые рассылки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StoreStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='ФИО сотрудника')),
                ('phone', models.CharField(max_length=30, verbose_name='Телефон (+998)')),
                ('role', models.CharField(choices=[('ADMIN', 'Администратор магазина'), ('MANAGER', 'Менеджер заказов'), ('COURIER', 'Курьер доставки'), ('CASHIER', 'Кассир / Оператор')], default='MANAGER', max_length=20, verbose_name='Должность')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='stores.store', verbose_name='Магазин')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'ordering': ['role', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Имя клиента')),
                ('phone', models.CharField(db_index=True, max_length=30, verbose_name='Телефон (+998)')),
                ('bonus_balance', models.PositiveIntegerField(default=0, verbose_name='Бонусный баланс (баллы)')),
                ('total_spent', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Всего потрачено (UZS)')),
                ('orders_count', models.PositiveIntegerField(default=0, verbose_name='Количество заказов')),
                ('last_order_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата последнего заказа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='stores.store', verbose_name='Магазин')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'ordering': ['-total_spent'],
                'unique_together': {('store', 'phone')},
            },
        ),
    ]
