# Generated by Django 6.1.1 on 2026-09-04 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='telegram_chat_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Telegram Chat ID'),
        ),
        migrations.AddField(
            model_name='customer',
            name='telegram_chat_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Telegram Chat ID'),
        ),
        migrations.AddField(
            model_name='customer',
            name='telegram_username',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Telegram Username'),
        ),
    ]
