# Generated by Django 6.1.1 on 2026-09-18 13:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_chatmessage_telegram_chat_id_and_more'),
        ('stores', '0009_store_theme_template'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storestaff',
            options={'ordering': ['-is_active', 'name'], 'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотрудники'},
        ),
        migrations.AddField(
            model_name='order',
            name='courier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_orders', to='orders.storestaff', verbose_name='Курьер доставки'),
        ),
        migrations.AddField(
            model_name='storestaff',
            name='is_courier',
            field=models.BooleanField(default=False, verbose_name='Является курьером'),
        ),
        migrations.AddField(
            model_name='storestaff',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='storestaff',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_profiles', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь аккаунта'),
        ),
        migrations.AlterField(
            model_name='storestaff',
            name='role',
            field=models.CharField(default='MANAGER', max_length=50, verbose_name='Должность'),
        ),
        migrations.CreateModel(
            name='StoreRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название роли')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='Описание роли')),
                ('is_system', models.BooleanField(default=False, verbose_name='Системная роль')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='stores.store', verbose_name='Магазин')),
            ],
            options={
                'verbose_name': 'Роль сотрудника',
                'verbose_name_plural': 'Роли сотрудников',
                'ordering': ['name'],
                'unique_together': {('store', 'name')},
            },
        ),
        migrations.AddField(
            model_name='storestaff',
            name='store_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_members', to='orders.storerole', verbose_name='Назначенная роль'),
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('dashboard', 'Boshqaruv paneli'), ('orders', 'Buyurtmalar'), ('customers', 'Mijozlar'), ('chats', 'Chat'), ('categories', 'Kategoriyalar'), ('products', 'Mahsulotlar'), ('discounts', 'Chegirma'), ('ikpu', 'IKPU'), ('warehouse', 'Omborxona'), ('broadcast', 'Rassilka'), ('promocodes', 'Promokod'), ('analytics', 'Manbalar'), ('banners', 'Banner'), ('telegram', 'Telegram bot'), ('payments', "To'lov turi"), ('delivery', 'Yetkazib berish'), ('branches', 'Filiallar'), ('staff', 'Xodimlar'), ('roles', 'Rollar'), ('settings', 'Sozlamalar'), ('channels', "Kanal bo'yicha yuborish")], max_length=50, verbose_name='Модуль')),
                ('can_view', models.BooleanField(default=False, verbose_name="Ko'rish (Просмотр)")),
                ('can_edit', models.BooleanField(default=False, verbose_name='Tahrirlash (Редактирование)')),
                ('can_delete', models.BooleanField(default=False, verbose_name="O'chirish (Удаление)")),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='orders.storerole', verbose_name='Роль')),
            ],
            options={
                'verbose_name': 'Право доступа роли',
                'verbose_name_plural': 'Права доступа ролей',
                'unique_together': {('role', 'module')},
            },
        ),
    ]
