# Generated by Django 6.1.1 on 2026-09-18 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_storestaff_options_order_courier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storestaff',
            name='current_lat',
            field=models.FloatField(blank=True, null=True, verbose_name='Текущая широта (GPS)'),
        ),
        migrations.AddField(
            model_name='storestaff',
            name='current_lng',
            field=models.FloatField(blank=True, null=True, verbose_name='Текущая долгота (GPS)'),
        ),
        migrations.AddField(
            model_name='storestaff',
            name='last_location_update',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последнее обновление геопозиции'),
        ),
    ]
