# Generated by Django 6.1.1 on 2026-09-26 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_storestaff_current_lat_storestaff_current_lng_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('CLICK', 'Click'), ('PAYME', 'Payme'), ('UZUM', 'Uzum Pay'), ('MULTICARD', 'Multicard'), ('CASH', 'Наличными при получении'), ('TERMINAL', 'Картой курьеру (терминал)')], default='CASH', max_length=20, verbose_name='Способ оплаты'),
        ),
    ]
