# Generated by Django 5.0.2 on 2026-09-27 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='custom_image_url',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='URL кастомного фото'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='custom_options',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Опции конструктора (JSON)'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='custom_summary',
            field=models.TextField(blank=True, default='', verbose_name='Описание сборки'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='variation_name',
            field=models.TextField(blank=True, verbose_name='Вариант (снапшот)'),
        ),
    ]
