# Generated by Django 6.1.1 on 2026-09-28 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_orderitem_custom_image_url_orderitem_custom_options_and_more'),
        ('stores', '0011_branch_is_accepting_orders_branch_manager_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storestaff',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_members', to='stores.branch', verbose_name='Филиал'),
        ),
    ]
