# Generated by Django 6.1.1 on 2026-09-28 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(db_index=True, max_length=32, verbose_name='Номер телефона (+998...)')),
                ('code', models.CharField(max_length=8, verbose_name='Код подтверждения')),
                ('purpose', models.CharField(choices=[('MERCHANT_REGISTER', 'Регистрация продавца'), ('MERCHANT_LOGIN', 'Вход продавца'), ('CUSTOMER_AUTH', 'Авторизация покупателя')], db_index=True, default='MERCHANT_REGISTER', max_length=32, verbose_name='Цель отправки')),
                ('is_verified', models.BooleanField(db_index=True, default=False, verbose_name='Подтвержден')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='Неудачные попытки ввода')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('expires_at', models.DateTimeField(db_index=True, verbose_name='Срок действия')),
            ],
            options={
                'verbose_name': 'SMS-подтверждение',
                'verbose_name_plural': 'SMS-подтверждения',
                'ordering': ['-created_at'],
            },
        ),
    ]
