# Generated by Django 6.1.1 on 2026-09-28 16:01

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_phoneverification'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(db_index=True, max_length=32, verbose_name='Номер телефона (+998...)')),
                ('code', models.CharField(max_length=8, verbose_name='Код подтверждения')),
                ('created_at', models.DateTimeField(db_index=True, default=django.db.models.functions.datetime.Now, verbose_name='Дата создания')),
                ('is_verified', models.BooleanField(db_index=True, default=False, verbose_name='Подтвержден')),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Срок действия')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='Неудачные попытки ввода')),
            ],
            options={
                'verbose_name': 'SMS-верификация',
                'verbose_name_plural': 'SMS-верификации',
                'ordering': ['-created_at'],
            },
        ),
    ]
