# Generated by Django 5.0.2 on 2026-09-09 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeadInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Ism / ФИО')),
                ('company', models.CharField(blank=True, max_length=255, verbose_name='Kompaniya / Компания')),
                ('phone', models.CharField(max_length=50, verbose_name='Telefon raqami / Номер телефона')),
                ('message', models.TextField(blank=True, verbose_name='Xabar / Сообщение')),
                ('source', models.CharField(default='landing_consultation', max_length=100, verbose_name='Manba / Источник')),
                ('status', models.CharField(choices=[('NEW', 'Yangi (Новый)'), ('CONTACTED', "Bog'lanildi (Связались)"), ('CONVERTED', "Mijoz bo'ldi (Сделка)"), ('REJECTED', 'Bekor qilindi (Отказ)')], default='NEW', max_length=20, verbose_name='Holat / Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana / Дата создания')),
            ],
            options={
                'verbose_name': 'Lid / Заявка на консультацию',
                'verbose_name_plural': 'Lidlar / Заявки на консультацию',
                'ordering': ['-created_at'],
            },
        ),
    ]
