# Generated by Django 6.1.1 on 2026-09-03 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('CLICK', 'Click'), ('PAYME', 'Payme'), ('UZUM', 'Uzum Pay'), ('SIMULATOR', 'Тестовый симулятор')], max_length=20, verbose_name='Платежный шлюз')),
                ('transaction_id', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='ID транзакции шлюза')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма транзакции (UZS)')),
                ('state', models.CharField(choices=[('INIT', 'Инициализирован'), ('PREPARED', 'Подготовлен (зарезервирован)'), ('COMPLETED', 'Успешно завершен'), ('CANCELLED', 'Отменен')], default='INIT', max_length=20, verbose_name='Статус')),
                ('payme_time', models.BigIntegerField(blank=True, null=True, verbose_name='Время Payme (timestamp)')),
                ('raw_payload', models.JSONField(blank=True, default=dict, verbose_name='Лог запроса шлюза')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='orders.order', verbose_name='Заказ')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='stores.store', verbose_name='Магазин')),
            ],
            options={
                'verbose_name': 'Платежная транзакция',
                'verbose_name_plural': 'Платежные транзакции',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StorePaymentSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('click_enabled', models.BooleanField(default=True, verbose_name='Включить Click')),
                ('click_service_id', models.CharField(blank=True, default='TEST_SERVICE_ID', max_length=60, verbose_name='Click Service ID')),
                ('click_merchant_id', models.CharField(blank=True, default='TEST_MERCHANT_ID', max_length=60, verbose_name='Click Merchant ID')),
                ('click_secret_key', models.CharField(blank=True, default='TEST_SECRET_KEY', max_length=100, verbose_name='Click Secret Key')),
                ('payme_enabled', models.BooleanField(default=True, verbose_name='Включить Payme')),
                ('payme_merchant_id', models.CharField(blank=True, default='TEST_PAYME_ID', max_length=60, verbose_name='Payme Merchant ID')),
                ('payme_secret_key', models.CharField(blank=True, default='TEST_SECRET_KEY', max_length=100, verbose_name='Payme Secret Key')),
                ('payme_test_mode', models.BooleanField(default=True, verbose_name='Payme Тестовый режим')),
                ('uzum_enabled', models.BooleanField(default=True, verbose_name='Включить Uzum Pay')),
                ('uzum_merchant_id', models.CharField(blank=True, default='TEST_UZUM_ID', max_length=60, verbose_name='Uzum Merchant ID')),
                ('uzum_secret_key', models.CharField(blank=True, default='TEST_SECRET_KEY', max_length=100, verbose_name='Uzum Secret Key')),
                ('cash_on_delivery_enabled', models.BooleanField(default=True, verbose_name='Наличными при получении')),
                ('terminal_on_delivery_enabled', models.BooleanField(default=True, verbose_name='Картой курьеру (терминал)')),
                ('test_simulator_enabled', models.BooleanField(default=True, verbose_name='Разрешить быстрый тестовый платеж (Симулятор для демонстрации)')),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_settings', to='stores.store', verbose_name='Магазин')),
            ],
            options={
                'verbose_name': 'Настройки платежей',
                'verbose_name_plural': 'Настройки платежей',
            },
        ),
    ]
