# Generated by Django 6.1.1 on 2026-09-26 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storepaymentsetting',
            name='multicard_app_id',
            field=models.CharField(blank=True, default='rhmt_test', max_length=100, verbose_name='Multicard Application ID'),
        ),
        migrations.AddField(
            model_name='storepaymentsetting',
            name='multicard_enabled',
            field=models.BooleanField(default=True, verbose_name='Включить Multicard'),
        ),
        migrations.AddField(
            model_name='storepaymentsetting',
            name='multicard_secret',
            field=models.CharField(blank=True, default='Pw18axeBFo8V7NamKHXX', max_length=120, verbose_name='Multicard Secret Key'),
        ),
        migrations.AddField(
            model_name='storepaymentsetting',
            name='multicard_store_id',
            field=models.CharField(blank=True, default='6', max_length=60, verbose_name='Multicard Store ID'),
        ),
        migrations.AddField(
            model_name='storepaymentsetting',
            name='multicard_test_mode',
            field=models.BooleanField(default=True, verbose_name='Multicard Тестовый режим'),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='provider',
            field=models.CharField(choices=[('CLICK', 'Click'), ('PAYME', 'Payme'), ('UZUM', 'Uzum Pay'), ('MULTICARD', 'Multicard'), ('SIMULATOR', 'Тестовый симулятор')], max_length=20, verbose_name='Платежный шлюз'),
        ),
    ]
