# Generated by Django 6.1.1 on 2026-09-07 10:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0007_store_admin_comment_store_company_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Наименование партнера / компании')),
                ('code', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Код партнера')),
                ('contact_person', models.CharField(blank=True, max_length=120, verbose_name='Контактное лицо')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('commission_rate', models.DecimalField(decimal_places=2, default=15.0, max_digits=5, verbose_name='Комиссионная ставка (%)')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Баланс вознаграждений (UZS)')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки / Условия')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата подключения')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Партнер / Селлер',
                'verbose_name_plural': 'Партнеры / Селлеры',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BillingDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_number', models.CharField(db_index=True, max_length=60, unique=True, verbose_name='Номер документа')),
                ('doc_type', models.CharField(choices=[('INVOICE', 'Счет на оплату'), ('ACT', 'Акт сверки / выполненных работ'), ('CONTRACT', 'Договор подписки'), ('RECONCILIATION', 'Акт взаиморасчетов')], default='INVOICE', max_length=30, verbose_name='Тип документа')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Сумма (UZS)')),
                ('status', models.CharField(choices=[('PAID', 'Оплачен'), ('PENDING', 'Ожидает оплаты'), ('OVERDUE', 'Просрочен'), ('CANCELLED', 'Аннулирован')], default='PENDING', max_length=20, verbose_name='Статус')),
                ('issue_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата выставления')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Срок оплаты')),
                ('description', models.TextField(blank=True, verbose_name='Назначение платежа / Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_documents', to='stores.store', verbose_name='Магазин / Сервер')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_documents', to='super_admin.partner', verbose_name='Партнер')),
            ],
            options={
                'verbose_name': 'Биллинг документ',
                'verbose_name_plural': 'Биллинг документы',
                'ordering': ['-issue_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ReconciliationEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('LICENSE', 'Покупка / продление лицензии'), ('TOPUP', 'Пополнение баланса мерчантом'), ('SMS', 'Списание за отправку SMS'), ('COMMISSION', 'Комиссия платформы'), ('ADJUSTMENT', 'Корректировка администратором'), ('REFUND', 'Возврат средств')], default='LICENSE', max_length=30, verbose_name='Тип операции')),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Дебет (Списание) UZS')),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Кредит (Пополнение) UZS')),
                ('balance_after', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Баланс после операции UZS')),
                ('description', models.CharField(max_length=255, verbose_name='Описание / Основание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время')),
                ('reference_doc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='super_admin.billingdocument', verbose_name='Связанный документ')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliation_entries', to='stores.store', verbose_name='Магазин / Сервер')),
            ],
            options={
                'verbose_name': 'Запись сверки (Акт)',
                'verbose_name_plural': 'Записи сверки (Акты)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TenantAdminNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_text', models.TextField(verbose_name='Текст служебной заметки')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='Закрепить сверху')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenant_admin_notes', to=settings.AUTH_USER_MODEL, verbose_name='Автор (Администратор)')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_notes', to='stores.store', verbose_name='Магазин / Сервер')),
            ],
            options={
                'verbose_name': 'Заметка администратора',
                'verbose_name_plural': 'Заметки администратора',
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TenantAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_name', models.CharField(blank=True, max_length=120, verbose_name='Имя пользователя')),
                ('action', models.CharField(max_length=120, verbose_name='Действие / Событие')),
                ('details', models.TextField(blank=True, verbose_name='Детали / Изменения')),
                ('ip_address', models.CharField(default='127.0.0.1', max_length=50, verbose_name='IP-адрес')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время события')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenant_audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='stores.store', verbose_name='Магазин / Сервер')),
            ],
            options={
                'verbose_name': 'Лог аудита тенанта',
                'verbose_name_plural': 'Логи аудита тенантов',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TenantSmsLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.CharField(db_index=True, max_length=40, verbose_name='Номер получателя (+998)')),
                ('message_text', models.TextField(verbose_name='Текст SMS')),
                ('sms_type', models.CharField(choices=[('AUTH', 'Код авторизации (OTP)'), ('ORDER', 'Статус заказа'), ('DELIVERY', 'Уведомление доставки'), ('SYSTEM', 'Системное оповещение')], default='AUTH', max_length=20, verbose_name='Тип SMS')),
                ('status', models.CharField(choices=[('DELIVERED', 'Доставлено'), ('SENT', 'Отправлено оператору'), ('FAILED', 'Ошибка отправки')], default='DELIVERED', max_length=20, verbose_name='Статус доставки')),
                ('cost', models.DecimalField(decimal_places=2, default=45.0, max_digits=8, verbose_name='Стоимость (UZS)')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Время отправки')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_logs', to='stores.store', verbose_name='Магазин / Сервер')),
            ],
            options={
                'verbose_name': 'Лог SMS',
                'verbose_name_plural': 'Логи SMS',
                'ordering': ['-sent_at'],
            },
        ),
    ]
