# Generated by Django 6.1.1 on 2026-09-15 10:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0009_store_theme_template'),
        ('super_admin', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TariffRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_plan', models.CharField(choices=[('START', 'Старт'), ('STANDARD', 'Стандарт'), ('PRO', 'Профессиональный'), ('ENTERPRISE', 'Корпоративный')], default='STANDARD', max_length=30, verbose_name='Запрошенный тариф')),
                ('period_months', models.PositiveIntegerField(default=1, verbose_name='Срок (мес.)')),
                ('calculated_days', models.PositiveIntegerField(default=30, verbose_name='Рассчитано дней')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Сумма заявки (UZS)')),
                ('payment_method', models.CharField(choices=[('BANK_TRANSFER', 'Перечисление / Счет на юрлицо'), ('CASH', 'Наличные / Офис'), ('BALANCE', 'С баланса магазина'), ('CLICK', 'Click'), ('PAYME', 'Payme'), ('UZUM', 'Uzum Pay'), ('OTHER', 'Другое')], default='BANK_TRANSFER', max_length=30, verbose_name='Способ оплаты')),
                ('contact_phone', models.CharField(blank=True, max_length=50, verbose_name='Контактный телефон')),
                ('notes', models.TextField(blank=True, verbose_name='Комментарий / Реквизиты мерчанта')),
                ('admin_notes', models.TextField(blank=True, verbose_name='Ответ / Заметка администратора')),
                ('status', models.CharField(choices=[('PENDING', 'Ожидает рассмотрения'), ('APPROVED', 'Одобрена и активирована'), ('REJECTED', 'Отклонена')], default='PENDING', max_length=20, verbose_name='Статус заявки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата подачи')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата обработки')),
                ('merchant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tariff_requests', to=settings.AUTH_USER_MODEL, verbose_name='Мерчант')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_tariff_requests', to=settings.AUTH_USER_MODEL, verbose_name='Обработал администратор')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tariff_requests', to='stores.store', verbose_name='Магазин / Сервер')),
            ],
            options={
                'verbose_name': 'Заявка на тариф',
                'verbose_name_plural': 'Заявки на тарифы',
                'ordering': ['-created_at'],
            },
        ),
    ]
