# Generated by Django 6.1.1 on 2026-09-03 10:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Название магазина')),
                ('subdomain', models.SlugField(unique=True, verbose_name='Поддомен (например: mystore)')),
                ('business_category', models.CharField(choices=[('FOOD', 'Еда, рестораны и доставка'), ('CLOTHING', 'Одежда, обувь и аксессуары'), ('ELECTRONICS', 'Электроника и гаджеты'), ('BEAUTY', 'Косметика и парфюмерия'), ('GROCERY', 'Продукты и супермаркет'), ('FLOWERS', 'Цветы и подарки'), ('SERVICES', 'Услуги и сервис'), ('OTHER', 'Другое')], default='FOOD', max_length=30, verbose_name='Категория бизнеса')),
                ('description_ru', models.TextField(blank=True, verbose_name='Описание магазина (RU)')),
                ('description_uz', models.TextField(blank=True, verbose_name='Описание магазина (UZ)')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='stores/logos/', verbose_name='Логотип')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='stores/banners/', verbose_name='Баннер / Обложка')),
                ('primary_color', models.CharField(default='#10B981', max_length=20, verbose_name='Основной цвет бренда (HEX)')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Телефон для связи (+998)')),
                ('instagram_username', models.CharField(blank=True, max_length=100, verbose_name='Instagram аккаунт')),
                ('telegram_channel', models.CharField(blank=True, max_length=100, verbose_name='Telegram канал/группа')),
                ('telegram_bot_token', models.CharField(blank=True, max_length=200, verbose_name='Токен Telegram-бота (от @BotFather)')),
                ('telegram_chat_id', models.CharField(blank=True, max_length=100, verbose_name='ID Telegram-группы/чата для заказов')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Адрес магазина (для самовывоза)')),
                ('pickup_enabled', models.BooleanField(default=True, verbose_name='Разрешить самовывоз')),
                ('courier_enabled', models.BooleanField(default=True, verbose_name='Разрешить курьерскую доставку')),
                ('delivery_price', models.DecimalField(decimal_places=2, default=20000, max_digits=12, verbose_name='Стоимость доставки (UZS)')),
                ('free_delivery_threshold', models.DecimalField(decimal_places=2, default=150000, max_digits=12, verbose_name='Бесплатная доставка от суммы (UZS)')),
                ('default_language', models.CharField(choices=[('ru', 'Русский'), ('uz', "O'zbekcha")], default='ru', max_length=5, verbose_name='Язык по умолчанию')),
                ('currency', models.CharField(default='UZS', max_length=10, verbose_name='Валюта')),
                ('is_active', models.BooleanField(default=True, verbose_name='Магазин активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stores', to=settings.AUTH_USER_MODEL, verbose_name='Владелец (Мерчант)')),
            ],
            options={
                'verbose_name': 'Магазин',
                'verbose_name_plural': 'Магазины',
                'ordering': ['-created_at'],
            },
        ),
    ]
