# Generated by Django 6.1.1 on 2026-09-03 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='about_us_ru',
            field=models.TextField(blank=True, verbose_name='О нас (RU)'),
        ),
        migrations.AddField(
            model_name='store',
            name='about_us_uz',
            field=models.TextField(blank=True, verbose_name='О нас (UZ)'),
        ),
        migrations.AddField(
            model_name='store',
            name='active_languages',
            field=models.JSONField(blank=True, default=list, verbose_name='Активные языки интерфейса'),
        ),
        migrations.AddField(
            model_name='store',
            name='business_type',
            field=models.CharField(choices=[('STORE', 'Интернет-магазин'), ('RESTAURANT', 'Ресторан / Кафе / Фастфуд'), ('SERVICES', 'Сфера услуг')], default='STORE', max_length=20, verbose_name='Тип бизнеса'),
        ),
        migrations.AddField(
            model_name='store',
            name='country',
            field=models.CharField(choices=[('UZ', 'Узбекистан (+998)'), ('KZ', 'Казахстан (+7)'), ('KG', 'Кыргызстан (+996)'), ('TJ', 'Таджикистан (+992)'), ('RU', 'Россия (+7)'), ('AE', 'ОАЭ (+971)')], default='UZ', max_length=5, verbose_name='Страна'),
        ),
        migrations.AddField(
            model_name='store',
            name='delivery_terms_ru',
            field=models.TextField(blank=True, verbose_name='Условия доставки (RU)'),
        ),
        migrations.AddField(
            model_name='store',
            name='delivery_terms_uz',
            field=models.TextField(blank=True, verbose_name='Условия доставки (UZ)'),
        ),
        migrations.AddField(
            model_name='store',
            name='delivery_time_estimate',
            field=models.CharField(default='30-45 мин', max_length=50, verbose_name='Примерное время доставки'),
        ),
        migrations.AddField(
            model_name='store',
            name='description_en',
            field=models.TextField(blank=True, verbose_name='Описание магазина (EN)'),
        ),
        migrations.AddField(
            model_name='store',
            name='platform_type',
            field=models.CharField(choices=[('ALL', 'Веб-сайт и Telegram Mini App'), ('WEB', 'Только веб-сайт'), ('TELEGRAM', 'Только Telegram-витрина')], default='ALL', max_length=20, verbose_name='Каналы продаж'),
        ),
        migrations.AddField(
            model_name='store',
            name='return_terms_ru',
            field=models.TextField(blank=True, verbose_name='Условия возврата (RU)'),
        ),
        migrations.AddField(
            model_name='store',
            name='return_terms_uz',
            field=models.TextField(blank=True, verbose_name='Условия возврата (UZ)'),
        ),
        migrations.AddField(
            model_name='store',
            name='working_hours',
            field=models.JSONField(blank=True, default=dict, verbose_name='График работы по дням недели'),
        ),
        migrations.AlterField(
            model_name='store',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Адрес главного филиала'),
        ),
        migrations.AlterField(
            model_name='store',
            name='default_language',
            field=models.CharField(choices=[('ru', 'Русский'), ('uz', "O'zbekcha"), ('en', 'English')], default='ru', max_length=5, verbose_name='Язык по умолчанию'),
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Название филиала')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('latitude', models.FloatField(default=41.2858, verbose_name='Широта (Lat)')),
                ('longitude', models.FloatField(default=69.2035, verbose_name='Долгота (Lng)')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Телефон филиала')),
                ('working_hours', models.CharField(default='09:00 - 23:00', max_length=100, verbose_name='Время работы')),
                ('is_main', models.BooleanField(default=False, verbose_name='Главный филиал')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='stores.store', verbose_name='Магазин')),
            ],
            options={
                'verbose_name': 'Филиал',
                'verbose_name_plural': 'Филиалы',
                'ordering': ['-is_main', 'name'],
            },
        ),
    ]
