# Generated by Django 6.1.1 on 2026-09-03 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_store_about_us_ru_store_about_us_uz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='facebook',
            field=models.CharField(blank=True, max_length=100, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='store',
            name='qr_bg_color',
            field=models.CharField(default='#FFFFFF', max_length=20, verbose_name='Fon rangi'),
        ),
        migrations.AddField(
            model_name='store',
            name='qr_code_color',
            field=models.CharField(default='#000000', max_length=20, verbose_name='QR kod rangi'),
        ),
        migrations.AddField(
            model_name='store',
            name='qr_main_text',
            field=models.CharField(default='Online buyurtma', max_length=100, verbose_name='Asosiy matn'),
        ),
        migrations.AddField(
            model_name='store',
            name='qr_main_text_color',
            field=models.CharField(default='#000000', max_length=20, verbose_name='Matn rangi'),
        ),
        migrations.AddField(
            model_name='store',
            name='qr_main_text_size',
            field=models.PositiveIntegerField(default=24, verbose_name='Matn hajmi'),
        ),
        migrations.AddField(
            model_name='store',
            name='qr_paper_size',
            field=models.CharField(choices=[('A5', "A5 qog'oz"), ('A6', "A6 qog'oz")], default='A5', max_length=10),
        ),
        migrations.AddField(
            model_name='store',
            name='qr_sub_text',
            field=models.CharField(default='Menyuni ochish uchun qr kodni skanerlang', max_length=200, verbose_name='Ikkilamchi matn'),
        ),
        migrations.AddField(
            model_name='store',
            name='qr_sub_text_color',
            field=models.CharField(default='#64748B', max_length=20, verbose_name='Ikkilamchi matn rangi'),
        ),
        migrations.AddField(
            model_name='store',
            name='qr_sub_text_size',
            field=models.PositiveIntegerField(default=8, verbose_name='Ikkilamchi matn hajmi'),
        ),
        migrations.AddField(
            model_name='store',
            name='tiktok',
            field=models.CharField(blank=True, max_length=100, verbose_name='TikTok'),
        ),
        migrations.AddField(
            model_name='store',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=100, verbose_name='WhatsApp'),
        ),
        migrations.AddField(
            model_name='store',
            name='youtube',
            field=models.CharField(blank=True, max_length=100, verbose_name='YouTube'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Manzil'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='branch',
            name='latitude',
            field=models.FloatField(default=41.2995, verbose_name='Lat'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='longitude',
            field=models.FloatField(default=69.2401, verbose_name='Lng'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Filial nomi'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='stores.store'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='working_hours',
            field=models.CharField(default='09:00 - 23:59', max_length=100),
        ),
        migrations.AlterField(
            model_name='store',
            name='active_languages',
            field=models.JSONField(blank=True, default=list, verbose_name='Активные языки'),
        ),
        migrations.AlterField(
            model_name='store',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Адрес филиала'),
        ),
        migrations.AlterField(
            model_name='store',
            name='business_category',
            field=models.CharField(choices=[('ACCESSORIES', 'Aksessuarlar'), ('AUTO', 'Avto ehtiyot qismlar'), ('ELECTRONICS', 'Elektronika'), ('BEAUTY', "Go'zallik va parvarish"), ('PETS', 'Hayvonlar uchun mahsulotlar'), ('DRINKS', 'Ichimliklar'), ('BOOKS', 'Kitoblar va ofis anjomlari'), ('CLOTHES', 'Kiyim-kechak'), ('APPLIANCES', 'Maishiy texnika'), ('FOOD', 'Oziq-ovqat'), ('SHOES', 'Poyabzal'), ('SPORT', 'Sport anjomlari'), ('HOME', 'Uy jihozlari'), ('OTHER', 'Boshqa')], default='FOOD', max_length=30, verbose_name='Категория бизнеса'),
        ),
        migrations.AlterField(
            model_name='store',
            name='business_type',
            field=models.CharField(choices=[('STORE', "Onlayn do'kon"), ('RESTAURANT', 'Restoran'), ('SERVICES', 'Xizmatlar')], default='STORE', max_length=20, verbose_name='Тип бизнеса'),
        ),
        migrations.AlterField(
            model_name='store',
            name='country',
            field=models.CharField(choices=[('UZ', "O'zbekiston"), ('KZ', "Qozog'iston"), ('TR', 'Turkiya'), ('RU', 'Rossiya'), ('KG', "Qirg'iziston"), ('OTHER', 'Boshqa')], default='UZ', max_length=10, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='store',
            name='courier_enabled',
            field=models.BooleanField(default=True, verbose_name='Курьерская доставка'),
        ),
        migrations.AlterField(
            model_name='store',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='default_language',
            field=models.CharField(default='uz', max_length=5, verbose_name='Основной язык'),
        ),
        migrations.AlterField(
            model_name='store',
            name='delivery_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Цена доставки (UZS)'),
        ),
        migrations.AlterField(
            model_name='store',
            name='delivery_time_estimate',
            field=models.CharField(default='30-45 мин', max_length=50, verbose_name='Время доставки'),
        ),
        migrations.AlterField(
            model_name='store',
            name='description_en',
            field=models.TextField(blank=True, verbose_name='Описание (EN)'),
        ),
        migrations.AlterField(
            model_name='store',
            name='description_ru',
            field=models.TextField(blank=True, verbose_name='Описание (RU)'),
        ),
        migrations.AlterField(
            model_name='store',
            name='description_uz',
            field=models.TextField(blank=True, verbose_name='Описание (UZ)'),
        ),
        migrations.AlterField(
            model_name='store',
            name='free_delivery_threshold',
            field=models.DecimalField(decimal_places=2, default=150000, max_digits=12, verbose_name='Бесплатная от (UZS)'),
        ),
        migrations.AlterField(
            model_name='store',
            name='instagram_username',
            field=models.CharField(blank=True, max_length=100, verbose_name='Instagram'),
        ),
        migrations.AlterField(
            model_name='store',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='store',
            name='phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Телефон (+998)'),
        ),
        migrations.AlterField(
            model_name='store',
            name='pickup_enabled',
            field=models.BooleanField(default=True, verbose_name='Самовывоз'),
        ),
        migrations.AlterField(
            model_name='store',
            name='platform_type',
            field=models.CharField(choices=[('ALL', 'Telegram va Veb-sayt'), ('WEB', 'Veb-sayt'), ('TELEGRAM', 'Telegram')], default='ALL', max_length=20, verbose_name='Каналы продаж'),
        ),
        migrations.AlterField(
            model_name='store',
            name='subdomain',
            field=models.SlugField(unique=True, verbose_name='Поддомен (.robosite.uz)'),
        ),
        migrations.AlterField(
            model_name='store',
            name='telegram_bot_token',
            field=models.CharField(blank=True, max_length=200, verbose_name='Токен бота'),
        ),
        migrations.AlterField(
            model_name='store',
            name='telegram_channel',
            field=models.CharField(blank=True, max_length=100, verbose_name='Telegram'),
        ),
        migrations.AlterField(
            model_name='store',
            name='telegram_chat_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='ID Telegram-чата'),
        ),
        migrations.AlterField(
            model_name='store',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='working_hours',
            field=models.JSONField(blank=True, default=dict, verbose_name='Расписание'),
        ),
        migrations.CreateModel(
            name='MerchantBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Balans (UZS)')),
                ('trial_days_left', models.PositiveIntegerField(default=7, verbose_name='Kunlik bepul sinov')),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='merchant_balance', to='stores.store')),
            ],
        ),
        migrations.CreateModel(
            name='MerchantCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=20, verbose_name='Karta raqami')),
                ('expiry', models.CharField(max_length=10, verbose_name='MM/YY')),
                ('is_main', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merchant_cards', to='stores.store')),
            ],
        ),
    ]
