# Generated by Django 6.1.1 on 2026-09-03 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_store_facebook_store_qr_bg_color_store_qr_code_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='telegram_welcome_message',
            field=models.TextField(blank=True, default="Assalomu alaykum! Do'konimizga xush kelibsiz. Quyidagi tugma orqali menyu bilan tanishishingiz va buyurtma berishingiz mumkin.", verbose_name='Приветственное сообщение бота'),
        ),
        migrations.AlterField(
            model_name='store',
            name='subdomain',
            field=models.SlugField(unique=True, verbose_name='Поддомен (.storebox.uz)'),
        ),
    ]
