# Generated by Django 6.1.1 on 2026-09-03 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_store_telegram_welcome_message_alter_store_subdomain'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='custom_domain',
            field=models.CharField(blank=True, max_length=100, verbose_name='Shaxsiy domen'),
        ),
        migrations.AddField(
            model_name='store',
            name='facebook_pixel_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='Facebook Pixel ID'),
        ),
        migrations.AddField(
            model_name='store',
            name='google_analytics_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='Google Analytics ID'),
        ),
        migrations.AddField(
            model_name='store',
            name='google_tag_manager_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='Google Tag Manager ID'),
        ),
        migrations.AddField(
            model_name='store',
            name='seo_description',
            field=models.TextField(blank=True, verbose_name="SEO ta'rif"),
        ),
        migrations.AddField(
            model_name='store',
            name='telegram_bot_username',
            field=models.CharField(blank=True, max_length=100, verbose_name='Bot Username'),
        ),
        migrations.AddField(
            model_name='store',
            name='telegram_button_name',
            field=models.CharField(default="Do'kon", max_length=50, verbose_name='Tugma nomi'),
        ),
        migrations.AddField(
            model_name='store',
            name='yandex_metrika_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='Yandex Metrika ID'),
        ),
    ]
