# Generated by Django 6.1.1 on 2026-09-06 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0005_store_custom_domain_store_facebook_pixel_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='theme_bg_color',
            field=models.CharField(default='#F8FAFC', max_length=20, verbose_name='Цвет фона сайта'),
        ),
        migrations.AddField(
            model_name='store',
            name='theme_business_niche',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Ниша магазина для ИИ'),
        ),
        migrations.AddField(
            model_name='store',
            name='theme_button_style',
            field=models.CharField(default='solid', max_length=30, verbose_name='Стиль кнопок'),
        ),
        migrations.AddField(
            model_name='store',
            name='theme_card_radius',
            field=models.CharField(default='3xl', max_length=20, verbose_name='Скругление карточек'),
        ),
        migrations.AddField(
            model_name='store',
            name='theme_card_style',
            field=models.CharField(default='modern', max_length=30, verbose_name='Стиль карточек товаров'),
        ),
        migrations.AddField(
            model_name='store',
            name='theme_image_aspect',
            field=models.CharField(default='portrait', max_length=20, verbose_name='Соотношение фото'),
        ),
    ]
