# Generated by Django 6.1.1 on 2026-09-07 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0006_store_theme_bg_color_store_theme_business_niche_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='admin_comment',
            field=models.TextField(blank=True, default='', verbose_name='Служебный комментарий'),
        ),
        migrations.AddField(
            model_name='store',
            name='company_name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Юр. лицо / Компания'),
        ),
        migrations.AddField(
            model_name='store',
            name='license_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Окончание лицензии'),
        ),
        migrations.AddField(
            model_name='store',
            name='license_plan',
            field=models.CharField(choices=[('START', 'Старт'), ('STANDARD', 'Стандарт'), ('PRO', 'Профессиональный'), ('ENTERPRISE', 'Корпоративный')], default='STANDARD', max_length=30, verbose_name='Тарифный план'),
        ),
    ]
