# Generated by Django 6.1.1 on 2026-09-07 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0007_store_admin_comment_store_company_name_and_more'),
        ('super_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stores', to='super_admin.partner', verbose_name='Партнер / Селлер'),
        ),
    ]
