# Generated by Django 5.0.2 on 2026-09-10 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0008_store_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='theme_template',
            field=models.CharField(choices=[('restaurant', 'Restoran & Yetkazib berish'), ('universal', "Universal do'kon"), ('boutique', 'Vizual Butik & Moda')], default='universal', max_length=30, verbose_name='Шаблон витрины'),
        ),
    ]
