# Generated by Django 6.1.1 on 2026-09-26 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0009_store_theme_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='license_plan',
            field=models.CharField(choices=[('START', 'Start'), ('STANDARD', 'Standard'), ('PRO', 'Pro'), ('ENTERPRISE', 'Enterprise')], default='START', max_length=30, verbose_name='Тарифный план'),
        ),
    ]
