# Generated by Django 6.1.1 on 2026-09-28 08:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0010_alter_store_license_plan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='is_accepting_orders',
            field=models.BooleanField(default=True, verbose_name='Принимает заказы онлайн'),
        ),
        migrations.AddField(
            model_name='branch',
            name='manager_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_branches', to=settings.AUTH_USER_MODEL, verbose_name='Управляющий филиала'),
        ),
        migrations.AddField(
            model_name='branch',
            name='manager_username',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Логин филиала'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
    ]
