# Generated by Django 6.1.1 on 2026-09-28 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0011_branch_is_accepting_orders_branch_manager_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='working_schedule',
            field=models.JSONField(blank=True, default=dict, verbose_name='Grafik (Dush-Yak)'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='working_hours',
            field=models.CharField(default='09:00 - 23:59', max_length=100, verbose_name='Ish vaqti matni'),
        ),
    ]
