# Generated by Django 6.1.1 on 2026-10-01 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0012_branch_working_schedule_alter_branch_working_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='is_constructor_enabled',
            field=models.BooleanField(default=True, verbose_name='Конструктор товаров активен на витрине'),
        ),
    ]
