# Generated by Django 6.1.1 on 2026-10-07 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0013_store_is_constructor_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='theme_template',
            field=models.CharField(choices=[('restaurant', 'Restoran & Yetkazib berish'), ('universal', "Universal do'kon"), ('boutique', 'Vizual Butik & Moda'), ('streetwear', 'Streetwear & Lookbook (222 FMA)')], default='universal', max_length=30, verbose_name='Шаблон витрины'),
        ),
    ]
