# Generated by Django 6.1.1 on 2026-10-07 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0014_alter_store_theme_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='business_category',
            field=models.CharField(choices=[('FLOWERS', "Gullar va sovg'alar"), ('FOOD', 'Oziq-ovqat'), ('CLOTHES', 'Kiyim-kechak'), ('ELECTRONICS', 'Elektronika'), ('BEAUTY', "Go'zallik va parvarish"), ('ACCESSORIES', 'Aksessuarlar'), ('AUTO', 'Avto ehtiyot qismlar'), ('PETS', 'Hayvonlar uchun mahsulotlar'), ('DRINKS', 'Ichimliklar'), ('BOOKS', 'Kitoblar va ofis anjomlari'), ('APPLIANCES', 'Maishiy texnika'), ('SHOES', 'Poyabzal'), ('SPORT', 'Sport anjomlari'), ('HOME', 'Uy jihozlari'), ('OTHER', 'Boshqa')], default='FOOD', max_length=30, verbose_name='Категория бизнеса'),
        ),
    ]
