# Generated by Django 6.1.1 on 2026-10-08 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0015_alter_store_business_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_slug', models.CharField(db_index=True, max_length=50, verbose_name='Servis identifikatori')),
                ('category', models.CharField(choices=[('pos', 'POS tizimlari'), ('warehouse', 'Omborxona'), ('delivery', 'Yetkazib berish'), ('payment', "To'lov tizimlari"), ('telephony_social', 'IP-telefoniya va Ijtimoiy tarmoqlar')], default='pos', max_length=30, verbose_name='Kategoriya')),
                ('name', models.CharField(max_length=100, verbose_name='Servis nomi')),
                ('is_connected', models.BooleanField(default=False, verbose_name='Ulandi')),
                ('is_active', models.BooleanField(default=False, verbose_name='Faol')),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='Ochiq parametrlar')),
                ('encrypted_credentials', models.TextField(blank=True, default='', verbose_name='Shifrlangan maxfiy kalitlar')),
                ('credentials_preview', models.JSONField(blank=True, default=dict, verbose_name="Niqoblangan kalitlar ko'rinishi")),
                ('last_sync_at', models.DateTimeField(blank=True, null=True, verbose_name='Oxirgi sinxronizatsiya')),
                ('last_sync_status', models.CharField(default='idle', max_length=30, verbose_name='Sinxronizatsiya holati')),
                ('last_sync_message', models.TextField(blank=True, default='', verbose_name='Xabar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrations', to='stores.store', verbose_name="Do'kon")),
            ],
            options={
                'verbose_name': "Do'kon integratsiyasi",
                'verbose_name_plural': "Do'kon integratsiyalari",
                'ordering': ['category', 'name'],
                'unique_together': {('store', 'service_slug')},
            },
        ),
    ]
