# Generated by Django 6.1.1 on 2026-10-08 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0016_storeintegration'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreIntegrationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_slug', models.CharField(db_index=True, max_length=50, verbose_name='Servis')),
                ('service_name', models.CharField(max_length=100, verbose_name='Nomi')),
                ('event_type', models.CharField(max_length=50, verbose_name='Voqea turi')),
                ('status', models.CharField(default='SUCCESS', max_length=20, verbose_name='Holat')),
                ('message', models.TextField(verbose_name='Xabar')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name="Batafsil ma'lumotlar")),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integration_logs', to='stores.store', verbose_name="Do'kon")),
            ],
            options={
                'verbose_name': 'Integratsiya jurnali',
                'verbose_name_plural': 'Integratsiya jurnallari',
                'ordering': ['-created_at'],
            },
        ),
    ]
