# Generated by Django 6.1.1 on 2026-09-03 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=100, verbose_name='Название (RU)')),
                ('name_uz', models.CharField(blank=True, max_length=100, verbose_name='Название (UZ)')),
                ('slug', models.SlugField(max_length=120, verbose_name='Слаг')),
                ('icon', models.CharField(blank=True, default='utensils', max_length=50, verbose_name='Иконка')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='Изображение')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='stores.store', verbose_name='Магазин')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['sort_order', 'id'],
                'unique_together': {('store', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=200, verbose_name='Название товара (RU)')),
                ('name_uz', models.CharField(blank=True, max_length=200, verbose_name='Название товара (UZ)')),
                ('slug', models.SlugField(max_length=220, verbose_name='Слаг')),
                ('description_ru', models.TextField(blank=True, verbose_name='Описание (RU)')),
                ('description_uz', models.TextField(blank=True, verbose_name='Описание (UZ)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена (UZS)')),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Старая цена (для акции)')),
                ('stock', models.IntegerField(default=10, verbose_name='Остаток на складе')),
                ('track_stock', models.BooleanField(default=True, verbose_name='Контролировать остатки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Хит продаж / Рекомендуем')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.category', verbose_name='Категория')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='stores.store', verbose_name='Магазин')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['-is_featured', '-created_at'],
                'unique_together': {('store', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/', verbose_name='Изображение')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Главное фото')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Фотография товара',
                'verbose_name_plural': 'Фотографии товара',
                'ordering': ['-is_primary', 'sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=100, verbose_name='Вариант / Опция (RU, например: Большой / 0.5L)')),
                ('name_uz', models.CharField(blank=True, max_length=100, verbose_name='Вариант / Опция (UZ, например: Katta / 0.5L)')),
                ('sku', models.CharField(blank=True, max_length=50, verbose_name='Артикул / SKU')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена варианта (UZS)')),
                ('stock', models.IntegerField(default=10, verbose_name='Остаток этого варианта')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='catalog.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Вариация товара',
                'verbose_name_plural': 'Вариации товаров',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
