# Generated by Django 6.1.1 on 2026-09-03 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, verbose_name='Название (EN)'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_en',
            field=models.TextField(blank=True, verbose_name='Описание (EN)'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='Название товара (EN)'),
        ),
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=4.9, max_digits=3, verbose_name='Рейтинг (звезды)'),
        ),
        migrations.AddField(
            model_name='product',
            name='reviews_count',
            field=models.PositiveIntegerField(default=15, verbose_name='Количество отзывов'),
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('dona', 'дона (шт)'), ('kg', 'кг'), ('liter', 'литр'), ('meter', 'метр'), ('portion', 'порция')], default='dona', max_length=20, verbose_name='Единица измерения'),
        ),
        migrations.AddField(
            model_name='productvariation',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, verbose_name='Вариант / Опция (EN, e.g. Large / 0.5L)'),
        ),
    ]
