# Generated by Django 6.1.1 on 2026-09-03 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_category_name_en_product_description_en_and_more'),
        ('stores', '0003_store_facebook_store_qr_bg_color_store_qr_code_color_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['-is_primary', 'sort_order', 'id']},
        ),
        migrations.AlterModelOptions(
            name='productvariation',
            options={'ordering': ['sort_order', 'id']},
        ),
        migrations.RemoveField(
            model_name='productvariation',
            name='sku',
        ),
        migrations.AddField(
            model_name='product',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Kirish narxi (UZS)'),
        ),
        migrations.AddField(
            model_name='product',
            name='ikpu_code',
            field=models.CharField(blank=True, max_length=50, verbose_name='IKPU'),
        ),
        migrations.AddField(
            model_name='product',
            name='margin',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=6, verbose_name='Marja (%)'),
        ),
        migrations.AddField(
            model_name='product',
            name='package_code',
            field=models.CharField(blank=True, max_length=50, verbose_name='Qadoqlash kodi'),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, default='utensils', max_length=50),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, verbose_name='Name (EN)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_ru',
            field=models.CharField(blank=True, max_length=100, verbose_name='Название (RU)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_uz',
            field=models.CharField(max_length=100, verbose_name="Kategoriya nomi (O'zbek)"),
        ),
        migrations.AlterField(
            model_name='category',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_en',
            field=models.TextField(blank=True, verbose_name='Description (EN)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_uz',
            field=models.TextField(blank=True, verbose_name="Ta'rif (O'zbek)"),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='Name (EN)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_ru',
            field=models.CharField(blank=True, max_length=200, verbose_name='Название (RU)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_uz',
            field=models.CharField(max_length=200, verbose_name="Mahsulot nomi (O'zbek)"),
        ),
        migrations.AlterField(
            model_name='product',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Eski narx (UZS)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Sotuv narxi (UZS)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=5.0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='product',
            name='reviews_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(max_length=220),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=10, verbose_name='Qolgan (dona)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='stores.store'),
        ),
        migrations.AlterField(
            model_name='product',
            name='track_stock',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('Dona', 'Dona'), ('Metr', 'Metr'), ('Kilogram', 'Kilogram'), ('Gramm', 'Gramm'), ('Santimetr', 'Santimetr'), ('Litr', 'Litr'), ('Kvadrat metr', 'Kvadrat metr'), ('Portsiya', 'Portsiya'), ('Tonna', 'Tonna'), ('Kub metr', 'Kub metr'), ('Upakovka', 'Upakovka'), ('Korobka', 'Korobka'), ('Pachka', 'Pachka'), ('Blok', 'Blok'), ('Milligram', 'Milligram'), ('Millilitr', 'Millilitr')], default='Dona', max_length=30, verbose_name="O'lchov birligi"),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.product'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, verbose_name='Option (EN)'),
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='name_ru',
            field=models.CharField(blank=True, max_length=100, verbose_name='Вариант (RU)'),
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='name_uz',
            field=models.CharField(max_length=100, verbose_name='Variant (UZ)'),
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='catalog.product'),
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='stock',
            field=models.IntegerField(default=10),
        ),
    ]
