# Generated by Django 6.1.1 on 2026-09-05 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_product_barcode'),
        ('stores', '0005_store_custom_domain_store_facebook_pixel_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='YesPosConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(max_length=255)),
                ('branch_id', models.CharField(max_length=100)),
                ('branch_name', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='yespos_connection', to='stores.store')),
            ],
        ),
        migrations.CreateModel(
            name='YesPosCategoryLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remote_category_id', models.CharField(max_length=100)),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yespos_links', to='catalog.category')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yespos_category_links', to='stores.store')),
            ],
            options={
                'unique_together': {('store', 'remote_category_id')},
            },
        ),
        migrations.CreateModel(
            name='YesPosProductLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remote_product_id', models.CharField(max_length=100)),
                ('remote_barcode', models.CharField(blank=True, max_length=100)),
                ('remote_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('remote_stock', models.IntegerField(default=0)),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yespos_links', to='catalog.product')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yespos_product_links', to='stores.store')),
            ],
            options={
                'unique_together': {('store', 'remote_product_id')},
            },
        ),
    ]
