# Generated by Django 6.1.1 on 2026-09-06 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_yesposconnection_yesposcategorylink_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image_url',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name='Rasm havolasi (URL)'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name='Rasm havolasi (URL)'),
        ),
    ]
