# Generated by Django 6.1.1 on 2026-09-24 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_category_image_url_product_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=120, verbose_name='Mijoz ismi')),
                ('author_phone', models.CharField(blank=True, max_length=30, verbose_name='Telefon')),
                ('rating', models.PositiveSmallIntegerField(default=5, verbose_name='Baho (1-5)')),
                ('comment', models.TextField(verbose_name='Sharh matni')),
                ('is_verified_buyer', models.BooleanField(default=True, verbose_name='Xarid tasdiqlangan')),
                ('is_approved', models.BooleanField(default=True, verbose_name='Tasdiqlangan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='catalog.product', verbose_name='Mahsulot')),
            ],
            options={
                'verbose_name': 'Sharh',
                'verbose_name_plural': 'Sharhlar',
                'ordering': ['-created_at'],
            },
        ),
    ]
