# Generated by Django 5.0.2 on 2026-09-25 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_productreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_tr',
            field=models.CharField(blank=True, max_length=100, verbose_name='Name (TR)'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_tr',
            field=models.TextField(blank=True, verbose_name='Description (TR)'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_tr',
            field=models.CharField(blank=True, max_length=200, verbose_name='Name (TR)'),
        ),
        migrations.AddField(
            model_name='productvariation',
            name='name_tr',
            field=models.CharField(blank=True, max_length=100, verbose_name='Option (TR)'),
        ),
    ]
