# Generated by Django 5.0.2 on 2026-09-26 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_category_name_tr_product_description_tr_and_more'),
        ('stores', '0010_alter_store_license_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='has_constructor',
            field=models.BooleanField(default=False, verbose_name='Конструктор товара'),
        ),
        migrations.CreateModel(
            name='ConstructorGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(max_length=150, verbose_name='Guruh nomi (UZ)')),
                ('name_ru', models.CharField(blank=True, max_length=150, verbose_name='Название группы (RU)')),
                ('name_en', models.CharField(blank=True, max_length=150, verbose_name='Group name (EN)')),
                ('group_type', models.CharField(choices=[('SINGLE', 'Один выбор (Radio)'), ('MULTIPLE', 'Несколько вариантов (Checkbox)'), ('QUANTITY', 'Количество (Счетчик шт.)')], default='SINGLE', max_length=20, verbose_name='Тип выбора')),
                ('min_required', models.PositiveIntegerField(default=0, verbose_name='Мин. количество для выбора')),
                ('max_allowed', models.PositiveIntegerField(default=1, verbose_name='Макс. количество для выбора')),
                ('is_required', models.BooleanField(default=False, verbose_name='Обязательный выбор')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='constructor_groups', to='catalog.product', verbose_name='Товар (основа конструктора)')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='constructor_groups', to='stores.store', verbose_name='Магазин')),
            ],
            options={
                'verbose_name': 'Группа опций конструктора',
                'verbose_name_plural': 'Группы опций конструктора',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ConstructorItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(max_length=150, verbose_name='Element nomi (UZ)')),
                ('name_ru', models.CharField(blank=True, max_length=150, verbose_name='Название элемента (RU)')),
                ('name_en', models.CharField(blank=True, max_length=150, verbose_name='Item name (EN)')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Добавочная цена (UZS)')),
                ('image_url', models.URLField(blank=True, default='', max_length=500, verbose_name='URL изображения')),
                ('icon', models.CharField(blank=True, default='', max_length=50, verbose_name='Иконка')),
                ('is_default', models.BooleanField(default=False, verbose_name='Выбран по умолчанию')),
                ('is_active', models.BooleanField(default=True, verbose_name='В наличии / Активен')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='catalog.constructorgroup', verbose_name='Группа конструктора')),
            ],
            options={
                'verbose_name': 'Элемент конструктора',
                'verbose_name_plural': 'Элементы конструктора',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
